### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by imfarzanansari** [VapiAI/docs-archived#101]
Path: /assistants/function-calling
if i am defining an azure function app that is triggered through an http request, how can i send parameters to the api end point?
there is no documentation available on how the receiving api gets the parameters passed by a function like properties

**Comment by bajajcodes** [comment]
@imfarzanansari, there are two types of functions available:

- `tools`: Account-scoped
- `functions`: Assistant-scoped

To pass parameters to a `ToolCall`, refer to the [Create Tool documentation](https://docs.vapi.ai/api-reference/tools/create-tool).

To pass parameters to a `function`, refer to the [Function Calling documentation](https://docs.vapi.ai/assistants/function-calling).

For receiving API functions of type `function`, the call gets parameters of type `OpenAIFunction` as defined in `components.schemas.OpenAIFunction` in the [API JSON documentation](https://api.vapi.ai/api-json).

For receiving API functions of type `ToolCall`, the call gets parameters of type `FunctionToolWithToolCall` as defined in `components.schemas.ToolCall` in the [API JSON documentation](https://api.vapi.ai/api-json).

The base schema is defined in `components.schemas.ServerMessage` and includes properties for tool calls and function calls.
