### ISSUE TITLE
Differences in Tools

### ISSUE THREAD

**Issue by kyeshmz** [VapiAI/docs-archived#105]
Might have misssed it, but cannot find any details on what the differences between the tools are or what the abbreviations are for.
```
    tools?: (CreateDtmfToolDTO | CreateEndCallToolDTO | CreateVoicemailToolDTO | CreateFunctionToolDTO | CreateGhlToolDTO | CreateMakeToolDTO | CreateTransferCallToolDTO)[];
```

Edit:
So it seems GHL and MakeTool are for the respective tools found here
[https://docs.vapi.ai/GHL](https://docs.vapi.ai/GHL)
 but the rest, its hard to tell what a Dtmf is ?

**Comment by nikhilro** [comment]
check: https://docs.vapi.ai/api-reference/tools/create-tool

**Comment by kyeshmz** [comment]
Where does it state anything in that document about what a CreateDtmfToolDTO or CreateVoicemailToolDTO is?

**Comment by nikhilro** [comment]
![image](https://github.com/user-attachments/assets/42745142-acf3-476f-a416-77be4a544ebe)

let us know if we can do something to make it confusing

**Comment by kyeshmz** [comment]
What is a DtmfTool? What does Dtmf abbreviate? How does that differ from a function tool? The documents are really does not invite anyone new coming into this space.
