### ISSUE TITLE
Issue on billing limit docs

### ISSUE THREAD

**Issue by vpd** [VapiAI/docs-archived#107]
Path: /billing/billing-limits
Doc refer to the link https://dashboard.vapi.ai/billing that is broken

At the same time the correct page https://dashboard.vapi.ai/org/billing has a disabled input for monthly limit, so it can't be edited.
I have figured out that after entering the card details you must click on "checkmark" icon (that is not highlighted), only after that you can edit the limit.

I believe the doc can be clarified.

**Comment by bajajcodes** [comment]
We will update it soon.
