### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by micklebt** [VapiAI/docs-archived#118]
Path: /billing/billing-limits

This appears to be a well-known issue for a while, but there is no solution apparently. Very frustrating to a **new user** evaluating the platform. I've wasted about 1 hour only to learn the problem is not me. 

![image](https://github.com/user-attachments/assets/571e9c85-59a7-4225-88f1-e22b16b20966)

**Comment by sahilsuman933** [comment]
This is not an issue, you just need to increase your monthly billing limit from the billing section.

**Comment by micklebt** [comment]
I have tried to do so. There is a circled red block and the field is not
enabled.
