### ISSUE TITLE
Issue on docs - use http or self-signed certificate for server events

### ISSUE THREAD

**Issue by bvschwartz** [VapiAI/docs-archived#123]
Path: /server-url/developing-locally

I'm getting this error when using a self-signed certificate for server events.

[ERROR] status-update Server URL Error: self-signed certificate

Is that not supported?  The docs don't say so.  I'm trying to using port forwarding rather than ngrok.  If I curl to my public URL using -k it works fine.

**Comment by sahilsuman933** [comment]
Send a call_id on discord channel.
