### ISSUE TITLE
Issue on Update "orgId" or move an Assistant to a different Organization

### ISSUE THREAD

**Issue by jimcxlp** [VapiAI/docs-archived#128]
Path: /api-reference/assistants/update-assistant
I am trying to figure out how to move an Assistant to a different Organization.  I assumed that I could do that with the Update Assistant, however, the orgId property is not available.

What am I missing?

Thanks

**Comment by sahilsuman933** [comment]
You can't move it. You can go get request on assistant and get the configuration and create a new assistant on different org
