### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by JeanEdern** [VapiAI/docs-archived#129]
Path: /server-url/events

It's not very easy to know how to retrieve the secret token in the params. 
Right now I need to log the params, find out where the secret token is, etc..
It would be great if the documentation showed an example of a server url call, so that we know very easily how to retrieve the secret token.

**Comment by sahilsuman933** [comment]
secret token are present in header as x-vapi-secret

**Comment by JeanEdern** [comment]
I think it'd be great to mention that in the documentation.
