### ISSUE TITLE
European VAPI Endpoint URL

### ISSUE THREAD

**Issue by heinz-leiser** [VapiAI/docs-archived#132]
Path: /support
Hello, 
I'm looking for the European VAPI endpoint URL to reduce latency for my voice assistant and to stay complient calls. 
Please advise.
Heinz

**Comment by nikhilro** [comment]
we currently don't have a dedicated european endpoint but the main one is complaint and latency should be _okay_

**Comment by heinz-leiser** [comment]
When I call a VAPI voice assistant via Twilio Phone, a POST request is made via webhook to https://api.vapi.ai/twilio/inbound_call.

In the Twilio Request Inspector, the following is displayed in the response body:

<Response>
    <Connect>
        <Stream url='wss://aws-us-west-2-production2-phone-call-websocket.vapi.ai/92677169-7ed1-40b8-9a6b-0764cf3c8de4/transport'>
            <Parameter name="callId" value='92677169-7ed1-40b8-9a6b-0764cf3c8de4' />
        </Stream>
    </Connect>
</Response>

This suggests that my call is being routed to AWS in the USA, causing latency of over 750ms and raising questions about data protection and compliance.

PS: The Twilio Endpoint is in Irland.

**Comment by heinz-leiser** [comment]
Do you have Appliance to install OnPrem?
