### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by DavisKoreal** [VapiAI/docs-archived#35]
Path: /call_functions

Your documentation is not very clear on custom functions

**Comment by JayC511** [comment]
Hey Davis! 

Is there any specific part that reads confusing, or isn't explaining something well? Or, what are you wanting to know that it's not conveying?

**Comment by DavisKoreal** [comment]
Hello, I did not directly understand the documentation on adding custom
functions on your dashboard. HOwever, after tinkering around a bit, I
finally got it. For future though, I would recommend a short example
showing the full workflow.

Sincerely.
