### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by swyxio** [VapiAI/docs-archived#47]
Path: /technical_support

you asked me to add things to a database but its not clear where to insert that??

**Comment by nikhilro** [comment]
Ya that example is terribly high-level. It expects you have your DB and backend setup. 

For first steps, I wouldn't even follow that. There is a no-code way to create an inbound support number. 

On dashboard.vapi.ai:
1. Create an assistant 
2. Buy a number
3. The number will have a dropdown to select which assistant you want to take calls to this number. 
4. That's it.

Now, if you want to get into advanced flows `assistant-request` comes in handy. Custom assistants for each incoming caller, memory based on who's calling, etc.

**Comment by bephrem1** [comment]
We're working on reworking our examples (as well as that example specifically).

> To add on we've created quickstart guides for [inbound calling](https://docs.vapi.ai/quickstart/phone/inbound) & [outbound calling](https://docs.vapi.ai/quickstart/phone/outbound), to address phone number creation + attaching assistants to them.

**Comment by bephrem1** [comment]
(closing for now)
