### ISSUE TITLE
Potential Issue on Pricing per minute

### ISSUE THREAD

**Issue by MikeCaldera** [VapiAI/docs-archived#56]
Path: /pricing

Pricing should be based on "per minute / second increments," especially for rapid hangups IE: cold calling B to B or fast food order taking. Obviously this depends on the application used but the longer the duration application the less likely to pose a billing problem. 

"Short duration calls can lead to an unexpected cost," by our potential customers who will be using this platform indirectly in the future. Unexpected billing poses a problem even though it states clearly in writing. Humans a funny characters when it comes to billing. Now when factoring in these current pricing for our Profit margin this makes this problem or issue more pronounced or amplified. 

Absolutely, you guys did great job and something everyone will eventually use but IMO the pricing should be based on actual usage since "everyone is billing everyone today!" If there weren't so many moving parts you could then predict a exact pricing model or even flat pricing model ... but because of different duration of phone calls under 1 minute the pricing will never be exact. I was a compliance officer at a wall street firm and I heard every customer complaint in the book even though it was in writing so may as well address this now. I hope this helps in the future. Mike

**Comment by nikhilro** [comment]
It's billed to the second. Please do send a PR if not clear :) No pressure though, we're rewriting the docs right now, will get to this, cc @bephrem1.
