### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by rachel-facere** [VapiAI/docs-archived#72]
Path: /custom-llm-guide

This guide and [this guide](https://docs.vapi.ai/assistants/custom-llm) both do not include a version for streaming. I want to host my own LLM and use it with Vapi.

[Open AI's docs](https://platform.openai.com/docs/api-reference/streaming) say they use server-sent events to stream. Is this what Vapi expects form LLMs?

**Comment by nikhilro** [comment]
yes, correct. we need you to SSE events back to us. will fix, for now chatgpt

**Comment by sahilsuman933** [comment]
It is added now.
