### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by ericsprauve** [VapiAI/docs-archived#75]
Path: https://docs.vapi.ai/api-reference/calls/create-phone-call

Create a phone call webpage doesn't seem to load correctly with an error in the console on "framework-785b255af5d8bea8.js:1 TypeError: Cannot destructure property 'mintConfig' of 't' as it is undefined."

**Comment by nikhilro** [comment]
yes, something up. mintlify looking into it. for now: api.vapi.ai/api

**Comment by sahilsuman933** [comment]
it is fixed now.
