### ISSUE TITLE
Date and Time

### ISSUE THREAD

**Issue by divyesh-puri** [VapiAI/docs-archived#86]
Assistance doesn't return the correct date and time. It's such a common thing since booking an appointment is one of the major use cases. I think the docs should include this or there should be a way to do this

**Comment by nikhilro** [comment]
Mind creating a ticket in #support channel in Discord for help like this

**Comment by divyesh-puri** [comment]
@nikhilro Don't you think if something comes up in support multiple times, that deserves to be in docs?
