### ISSUE TITLE
Vapi/LLM ignoring results of function calls

### ISSUE THREAD

**Issue by rachel-facere** [VapiAI/docs-archived#94]
Hi, I wanted to ask if there has been the change in how Vapi handles function calls in the last few weeks. 

We are developing a voice assistant and our function calls often return instructions like "Failed to find X, please use step Y" as well as information. But recently we have noticed that Vapi has been calling these functions while speaking more naturally (instead of saying "wait a moment" while calling the function). It has also been ignoring both information and instructions from function calls, as well as hallucinating responses much more often.

I wanted to know if this is because of a change in gpt-4 and gpt-4o or a change in the Vapi pipeline. And if you have any advice on defending against hallucinations.

**Comment by nikhilro** [comment]
No change in Vapi pipeline. GPT4o _is_ used in the GPT4 cluster, that could be it but am unsure. We expose all the logs now. If you check the calls page on the dashboard, there should be a play-to-play. Discord #support channel is the best place to get help since we have a tracking system there.
